### ISSUE TITLE
target_feat is numerical but is interpreted as categorical

### ISSUE THREAD

**Issue by bm765** [fbdesignpro/sweetviz#100]
Hi,

thanks for bringing this software to life!!! :-)

If I execute the following code, I get the error below. Am I doing something wrong here?

```python3
import sweetviz as sv
import pandas as pd
import io
import sys

print("sys.version=", sys.version)
print("sv.__version__=", sv.__version__)
print("pd.__version__=", pd.__version__)

myString = """
-0.029905, 1.0, 2.0
 1.803806, 0.5, 2.0
 0.729614, 2.0, 2.0
 0.702528, 0.5, 1.0
 0.718835, 1.0, 2.0
 0.603640, 2.0, 2.0
 0.492969, 2.0, 2.0
 0.573862, 0.5, 2.0
 4.357443, 0.5, 2.0
 0.129235, 2.0, 1.0
"""

df = pd.read_csv(io.StringIO(myString), sep=',', header=None)
df.columns=['a', 'b', 'c']

df['a'] = df.a.astype(float)

print("type(df.a.iloc[0])=", type(df.a.iloc[0]))

my_report = sv.analyze(df, target_feat="a")
```

error:
```

sys.version= 3.8.7 (default, Dec 21 2020, 21:23:03) 
[GCC 5.4.0 20160609]
sv.__version__= 2.1.3
pd.__version__= 1.3.2
type(df.a.iloc[0])= <class 'numpy.float64'>
Feature: a (TARGET)                          |██▌       | [ 25%]   00:00 -> (00:00 left)Gtk-Message: 20:00:57.393: Failed to load module "appmenu-gtk-module"
Feature: a (TARGET)                          |█████     | [ 50%]   00:00 -> (00:00 left)Traceback (most recent call last):
  File "/home/user/PycharmProjects/my_project/file01.py", line 31, in <module>
    my_report = sv.analyze(df, target_feat="a")
  File "/home/user/venv/numba38/lib/python3.8/site-packages/sweetviz/sv_public.py", line 12, in analyze
    report = sweetviz.DataframeReport(source, target_feat, None,
  File "/home/user/venv/numba38/lib/python3.8/site-packages/sweetviz/dataframe_report.py", line 238, in __init__
    this_feat = FeatureToProcess(cur_order_index,
  File "/home/user/venv/numba38/lib/python3.8/site-packages/sweetviz/sv_types.py", line 77, in __init__
    raise ValueError("TARGET values can only be of NUMERICAL or BOOLEAN type for now.\n"
ValueError: TARGET values can only be of NUMERICAL or BOOLEAN type for now.
CATEGORICAL type was detected; if you meant the target to be
NUMERICAL, use a FeatureConfig(force_num=...) object.
Feature: a (TARGET)                          |█████     | [ 50%]   00:01 -> (00:01 left)
```

**Comment by fbdesignpro** [comment]
Hello @bm765, thank you for the good words on sweetviz! I apologize for the long delay in answering. If you or anyone could still use this information, the answer is as follows:

As you may suspect, the system is inferring the data to be categorical, since there are so few different values. You can change the threshold under which that determination is made (i.e. how many different values can a categorical feature have) using a custom configuration file.

**But**; this is not the best way to go here.

Simply **use a `FeatureConfig` object to tell Sweetviz the target category should be forced to be numerical**:
```
feature_config = sweetviz.FeatureConfig(force_num=["a"])
```
Then use it when generating the report:
```
my_report = sweetviz.analyze(df, target_feat="a", feat_cfg=feature_config)
```

**Comment by narendrareddig** [comment]
This is helped for me.
